[build]
  command = "mkdir -p functions && GOOS=linux GOARCH=amd64 go build -o functions/hello main.go"
  functions  = "functions"
  publish = "public"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/hello/:splat"
  status = 200
